export type OrderSnapshot = {
  deliverySequence: number;
  customerName: string;
  address: string;
  mobile: string;
  route: string;
  type: string;
  deliveryDate: string;
  note: string | null;
  items: string[];
};

export const orderSnapshotData: OrderSnapshot[] = [
  {
    deliverySequence: 1,
    customerName: 'Sandeep',
    address: 'Flatno.303, tower b-4, Tulip Violet, Sector 69, Gurgaon',
    mobile: '8860920951',
    route: 'Dipankar',
    type: 'Regular Veggie Bag',
    deliveryDate: '2023-MAR-01',
    note: null,
    items: [
      '2kg Potato (Alu)',
      'Potato (Alu)',
      'Onions (Pyaz)',
      'Tomatoes (Tamatar) DESI',
      'Garlic (lehsun)',
      'Ginger (Adrak)',
      'Coriander (Dhaniya)',
      'Lemons (Neebu)',
      'Chillies (Hari Mirch teekhi)',
      'Cabbage (Bandgobhi)',
      'Bottle Gourd (Lauki/Ghiya) Long',
      'Apple Gourd (tinda)',
      'Cauliflower (Foolgobhi)',
      'Gwar Fali (Cluster Beans)',
      'Cucumber (Kheera)',
      'Beetroots',
    ],
  },
  {
    deliverySequence: 2,
    customerName: 'Shruti Gaggar',
    deliveryDate: '2023-MAR-01',
    address: '1404, tower 6, Orchid Petals, Sector 49, Gurgaon',
    mobile: '9711880218',
    route: 'Dipankar',
    type: 'Regular Veggie Bag',
    note: null,
    items: [
      'Onions (Pyaz)',
      '2kg Tomatoes (Tamatar) DESI',
      'Tomatoes (Tamatar) DESI',
      '200gm Ginger (Adrak)',
      '250gm Coriander (Dhaniya)',
      'Coriander (Dhaniya)',
      '200gm Lemons (Neebu)',
      'Cabbage (Bandgobhi)',
      '250gm Apple Gourd (tinda)',
      'Cucumber (Kheera)',
      '500gm Baby Corn',
      'Baby Corn',
      'Orange Carrots (Gajar)',
      'Radish (Muli)',
      'Beetroots',
    ],
  },
  {
    deliverySequence: 3,
    customerName: 'Ishani',
    address: '1664, 3rd Floor, Sector 52, Gurgaon',
    mobile: '9643408451',
    deliveryDate: '2023-MAR-01',

    route: 'Dipankar',
    type: 'Regular Veggie Bag',
    note: null,
    items: [
      'Potato (Alu)',
      'Onions (Pyaz)',
      'Tomatoes (Tamatar) DESI',
      'Garlic (lehsun)',
      'Ginger (Adrak)',
      'Coriander (Dhaniya)',
      'Lemons (Neebu)',
      'Chillies (Hari Mirch teekhi)',
      'Cabbage (Bandgobhi)',
      'Apple Gourd (tinda)',
      
      'Cauliflower (Foolgobhi)',
      'Cucumber (Kheera)',
      'Lotus STEM (Kamal Kakdi)',
      'Orange Carrots (Gajar)',
      'LemonGrass',
      'Geloy',
    ],
  },
  {
    deliverySequence: 4,
    customerName: 'Dr Manisha',
    address: '8B, Tower-3, The Hibiscus, Sector 50, Gurgaon',
    mobile: '9650090303',
    deliveryDate: '2023-MAR-01',

    route: 'Dipankar',
    type: 'Regular Veggie Bag',
    note: 'add 2 kgs of staples all',
    items: [
      '2kg Onions (Pyaz)',
      'Onions (Pyaz)',
      '2kg Tomatoes (Tamatar) DESI',
      'Tomatoes (Tamatar) DESI',
      'Garlic (lehsun)',
      'Ginger (Adrak)',
      'Coriander (Dhaniya)',
      'Lemons (Neebu)',
      'Chillies (Hari Mirch teekhi)',
      'Cabbage (Bandgobhi)',
      'Apple Gourd (tinda)',
      'Cauliflower (Foolgobhi)',
      'Cucumber (Kheera)',
      'Bitter Gourd (Karela)',
      'Radish (Muli)',
    ],
  },
  {
    deliverySequence: 5,
    customerName: 'Aayush Chopra',
    address: 'H43, Ground Floor, Residency Greens, Sector 46, Gurgaon',
    mobile: '9999088800',
    deliveryDate: '2023-MAR-01',

    route: 'Dipankar',
    type: 'Regular Veggie Bag',
    note: null,
    items: [
      '2kg Potato (Alu)',
      'Potato (Alu)',
      'Potato (Alu)',
      '2kg Onions (Pyaz)',
      'Onions (Pyaz)',
      '2kg Tomatoes (Tamatar) DESI',
      'Tomatoes (Tamatar) DESI',
      'Garlic (lehsun)',
      'Ginger (Adrak)',
      'Coriander (Dhaniya)',
      'Lemons (Neebu)',
      'Chillies (Hari Mirch teekhi)',
      'Cabbage (Bandgobhi)',
      'Bottle Gourd (Lauki/Ghiya) Long',
      'Apple Gourd (tinda)',
      'Cauliflower (Foolgobhi)',
      'Gwar Fali (Cluster Beans)',
      'Capsicum (Shimla Mirch)',
    ],
  },
  {
    deliverySequence: 6,
    customerName: 'Rupinder',
    address: '15, Bodhi Marg, DLF phase 1, Sector 26, Gurgaon',
    mobile: '9958482714',
    route: 'Dipankar',
    deliveryDate: '2023-MAR-01',

    type: 'Regular Veggie Bag',
    note: null,
    items: [
      'Potato (Alu)',
      '2kg Onions (Pyaz)',
      'Onions (Pyaz)',
      '2kg Tomatoes (Tamatar) DESI',
      'Tomatoes (Tamatar) DESI',
      '100gm Garlic (lehsun)',
      'Garlic (lehsun)',
      '250gm Ginger (Adrak)',
      'Coriander (Dhaniya)',
      '500gm Lemons (Neebu)',
      'Lemons (Neebu)',
      'Lemons (Neebu)',
      'Chillies (Hari Mirch teekhi)',
      'Bottle Gourd (Lauki/Ghiya) Long',
      'Apple Gourd (tinda)',
      'Cauliflower (Foolgobhi)',
      '1kg Cucumber (Kheera)',
    ],
  },
  // Add more orders as needed
];
